In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pickle

In [2]:
df = pd.read_csv("instagram_analytics.csv")
df

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,5,7,34,4327,6230,0.0385,899,100,7,medium
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,...,10,21,68,7451,8268,0.0663,805,122,5,viral
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,2,1,22,1639,2616,0.0531,758,115,8,high
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,0,7,0,2877,3171,0.0309,402,115,7,medium
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,8,5,21,5350,8503,0.0221,155,112,9,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,IG0029995,5,brand,10739,carousel,Travel,Reels Feed,0,2024-12-18 10:00:00,2024-12-18,...,1,2,5,1564,2493,0.0032,124,127,8,low
29995,IG0029996,3,brand,10018,image,Beauty,Hashtags,0,2025-05-05 15:00:00,2025-05-05,...,2,1,7,2042,2492,0.0209,310,114,12,low
29996,IG0029997,18,creator,7486,image,Photography,Explore,1,2025-05-26 10:00:00,2025-05-26,...,10,16,59,5887,7528,0.0558,223,115,4,high
29997,IG0029998,6,creator,10034,carousel,Technology,Explore,1,2025-08-02 19:00:00,2025-08-02,...,3,0,19,5372,6312,0.0333,978,124,4,medium
29998,IG0029999,9,creator,6916,image,Technology,Explore,1,2025-04-15 20:00:00,2025-04-15,...,1,1,5,4019,5678,0.0100,272,126,11,low

In [3]:
df.shape

(29999, 23)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   post_id                   29999 non-null  object
 1   account_id                29999 non-null  int64
 2   account_type              29999 non-null  object
 3   follower_count            29999 non-null  int64
 4   media_type                29999 non-null  object
 5   content_category          29999 non-null  object
 6   traffic_source            29999 non-null  object
 7   has_call_to_action        29999 non-null  int64
 8   post_datetime             29999 non-null  object
 9   post_date                 29999 non-null  object
 10  post_hour                 29999 non-null  int64
 11  day_of_week               29999 non-null  object
 12  likes                     29999 non-null  int64
 13  comments                  29999 non-null  int64
 14  shares                    29999 non-null  int64
 15  saves                     29999 non-null  int64
 16  reach                     29999 non-null  int64
 17  impressions               29999 non-null  int64
 18  engagement_rate           29999 non-null  float64
 19  followers_gained          29999 non-null  int64
 20  caption_length            29999 non-null  int64
 21  hashtags_count            29999 non-null  int64
 22  performance_bucket_label  29999 non-null  object
dtypes: float64(1), int64(13), object(9)
memory usage: 5.3+ MB

In [5]:
df.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,5,7,34,4327,6230,0.0385,899,100,7,medium
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,...,10,21,68,7451,8268,0.0663,805,122,5,viral
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,2,1,22,1639,2616,0.0531,758,115,8,high
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,0,7,0,2877,3171,0.0309,402,115,7,medium
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,8,5,21,5350,8503,0.0221,155,112,9,low

In [6]:
df.tail()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
29994,IG0029995,5,brand,10739,carousel,Travel,Reels Feed,0,2024-12-18 10:00:00,2024-12-18,...,1,2,5,1564,2493,0.0032,124,127,8,low
29995,IG0029996,3,brand,10018,image,Beauty,Hashtags,0,2025-05-05 15:00:00,2025-05-05,...,2,1,7,2042,2492,0.0209,310,114,12,low
29996,IG0029997,18,creator,7486,image,Photography,Explore,1,2025-05-26 10:00:00,2025-05-26,...,10,16,59,5887,7528,0.0558,223,115,4,high
29997,IG0029998,6,creator,10034,carousel,Technology,Explore,1,2025-08-02 19:00:00,2025-08-02,...,3,0,19,5372,6312,0.0333,978,124,4,medium
29998,IG0029999,9,creator,6916,image,Technology,Explore,1,2025-04-15 20:00:00,2025-04-15,...,1,1,5,4019,5678,0.0100,272,126,11,low

In [7]:
df = df.dropna()

In [38]:
X = df.drop(target_column, axis=1)
y = df[target_column]
X
y

0        2
1        3
2        0
3        2
4        1
        ..
29994    1
29995    1
29996    0
29997    2
29998    1
Name: performance_bucket_label, Length: 29999, dtype: int64

In [35]:
print(df.isnull().sum())

post_id                     0
account_id                  0
account_type                0
follower_count              0
media_type                  0
content_category            0
traffic_source              0
has_call_to_action          0
post_datetime               0
post_date                   0
post_hour                   0
day_of_week                 0
likes                       0
comments                    0
shares                      0
saves                       0
reach                       0
impressions                 0
engagement_rate             0
followers_gained            0
caption_length              0
hashtags_count              0
performance_bucket_label    0
dtype: int64

In [20]:
target_column = "performance_bucket_label"
target_column

'performance_bucket_label'

In [21]:
print(df.columns)

Index(['post_id', 'account_id', 'account_type', 'follower_count', 'media_type',
       'content_category', 'traffic_source', 'has_call_to_action',
       'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes',
       'comments', 'shares', 'saves', 'reach', 'impressions',
       'engagement_rate', 'followers_gained', 'caption_length',
       'hashtags_count', 'performance_bucket_label'],
      dtype='object')

In [36]:
print(X.columns)

Index(['post_id', 'account_id', 'account_type', 'follower_count', 'media_type',
       'content_category', 'traffic_source', 'has_call_to_action',
       'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes',
       'comments', 'shares', 'saves', 'reach', 'impressions',
       'engagement_rate', 'followers_gained', 'caption_length',
       'hashtags_count'],
      dtype='object')

In [22]:
label_encoder = LabelEncoder()
df[target_column] = label_encoder.fit_transform(df[target_column])

In [39]:



with open("features.pkl", "wb") as f:
    pickle.dump(X.columns.tolist(), f)

In [40]:
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)

In [41]:
X = df.drop(target_column, axis=1)
y = df[target_column]

In [42]:
categorical_cols = X.select_dtypes(include=['object']).columns
encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))
    encoders[col] = le

In [43]:
with open("encoders.pkl", "wb") as f:
    pickle.dump(encoders, f)

In [28]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [29]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [31]:

y_pred = model.predict(X_test)
y_pred

array([3, 3, 3, ..., 2, 3, 0], shape=(6000,))

In [32]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8513333333333334

In [33]:
with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

In [34]:
print("Model saved successfully")

Model saved successfully